# Configuration du serveur HTTP

server {
    # Port et hôte pour ce serveur
    listen 8020;
    host 127.0.0.1;

    # Serveur par défaut
    server_name myserver.local;

    # Pages d'erreur par défaut
    error_page 404 /error_pages/404.html;
    error_page 500 /error_pages/500.html;

    # Limitation de la taille du corps du client
    client_max_body_size 4M;

    # Routes
    location / {
        # Répertoire racine pour cette route
        root /www/html;
        index index.html;
        methods GET POST;
    }

    location /images/ {
        # Répertoire pour les fichiers d'images
        root /www/images;
        autoindex on; # Activer le listing des répertoires
    }

    location /upload {
        # Répertoire pour les uploads
        root /www/uploads;
        methods POST; # Seules les méthodes POST sont acceptées
        upload_store /uploads/; # Répertoire où les fichiers seront sauvegardés
    }

    location /cgi-bin/ {
        # Exécuter les scripts CGI
        cgi on;
        cgi_bin /cgi-bin/;
        methods GET POST;
        extension .php;
    }

    # Redirection HTTP
    location /old-page {
        return 301 /new-page;
    }
}
