server {

    # temps en seconde avant que le serveur ne ferme la connexion sans nouvelle requette...
    keepalive_timeout 65;
    # temps pour recevoir le body apres avoir reçu les entêtes
    client_body_timeout 60;
    # temps max pour recevoir les entêtes apres avoir ouvert la connexion
    client_header_timeout 10;
    

    listen 8090;
    host 127.0.0.1;

    server_name myserver.local;

    error_page_404 /error_pages/404.html;
    error_page_500 /error_pages/500.html;

    client_max_body_size 4M;

    location / {
        root /www/html;
        index index.html;
        methods GET POST;
    }

    location /images/ {
        root /www/images;
        autoindex on
    }

    location /upload {
        root /www/uploads;
        methods POST
        upload_store /uploads/
    }

    location /cgi-bin/ {
        root /www/cgi-bin;
        cgi on;
        cgi_bin /cgi-bin/;
        methods GET POST;
        extension .php;
    }

    location /old-page {
        return 301 /new-page;
    }
}
