
server {

    listen 8000;
    host 127.0.0.1;
    server_name tests.42.fr;

    location /php/ {
        root /www/testsScripts/php/;
        index index.php;
        methods GET POST;
    }

    location /cgi-bin/ {
        root /www/testsScripts/cgi-bin/;
        cgi on;
        cgi_bin /cgi-bin/;
        methods GET POST DELETE;
        exe /usr/bin/env;
        extension .cgi .sh .php;
    }

    location /files/ {
        root /www/testsScripts/files/;
        autoindex on;
        methods PUT GET;
    }

    location / {
        root /www/testsScripts/html/;
        index index.html;
        methods GET POST;
    }

    location /google/ {
        return 301 https://www.google.fr;
    }

    location /sessions/ {
        return 301 http://127.0.80.80:8080;
    }
}

server {
    listen 8080;
    host 127.0.80.80;
    server_name session.42.fr;

    location / {
        root /www/testSession/;
        index index.php;
        methods GET POST;
    }

    location .php {
        root /www/testSession/;
        cgi on;
        exe /usr/bin/php-cgi;
        methods POST GET;
    }

}